"""
Django settings for different environment.

Generated by 'django-admin startproject' using Django 4.0.3.

The original settings.py has been copied to base.py, and duplicated dev.py and prod.py from base.py.
The author uses prod.py for this project only due to the scale of the project.
If project will be expanding bigger, then it is suggested to do development on dev.py, and production on prod.py.
"""